#!/usr/bin/perl -w

use strict;

my $time = -1;
my $last_packet_sent = -1;
my $desired_direction = shift @ARGV;

print STDERR "Looking at direction $desired_direction...\n";

my $used = 0;
my $available = 0;

my $tsoffset = -1;

while ( <> ) {
  chomp;
  my ( $dir, $new_time, $del, $ms_old ) = split /\s+/, $_;

  next unless $dir eq $desired_direction;

  $new_time = int( $new_time * 1000 + 0.5 );

  if ( $tsoffset == -1 ) {
    $tsoffset = $new_time;
  }

#  $new_time -= $tsoffset;

  next unless ( $new_time >= 60000 );

  if ( m{/.*%} ) {
    my ( $dir, $sec, $this_used, $slash, $this_avail ) = split /\s+/, $_;
    $used += $this_used;
    $available += $this_avail;
    next;
  }

  if ( $time == -1 ) {
    $time = $new_time;
  }

  while ( $time < $new_time ) {
    my $age = $time - $last_packet_sent;
    printf "%f %d\n", $time, $age;
    $time++;
  }

  my $new_last_packet_sent = $new_time - $ms_old;
  die unless ( $new_last_packet_sent >= $last_packet_sent );
  $last_packet_sent = $new_last_packet_sent;
}

printf STDERR "Used $used / $available => %f %% \n", 100.0 * $used / $available;
